test:
	go test -v -timeout 40m -coverprofile=coverage.txt `go list ./... | grep -E  'auth|conf|cdn|storage|rtc|internal'`

unittest:
	go test -race -v ./auth/...
	go test -race -v ./conf/...
	go test -race -v ./internal/...
